# Generated by Django 5.0.6 on 2024-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(upload_to="media/profile_pic"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "STAFF"), (3, "STUDENT")],
                default=1,
                max_length=50,
            ),
        ),
    ]
