# Generated by Django 5.0.7 on 2024-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_staffnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffnotification",
            name="status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
