# Generated by Django 5.0.7 on 2024-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_studentfeedback_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafffeedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
