# Generated by Django 5.0.7 on 2024-07-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_studentleave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentleave",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.student"
            ),
        ),
    ]
