# Generated by Django 5.0.7 on 2024-07-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_student_leave"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student_Leave",
        ),
    ]
